### ISSUE TITLE
Array out of bounds

### ISSUE THREAD

**Issue by raver1975** [smigielski/q-behave#1]
in QLearningMachine.cpp:

while (sum<rand){
    nextAction = &stateActions.actions[i];
    maxQuality = calculateExp(stateActions.actions[i].quality)/sigma*100;
    sum+= maxQuality;
    i++;
}

sometimes i will be out of bounds, crashing the program. 
I fixed it like this, not sure if this is correct:
while (sum<rand&&i<stateActions.actionCount){

**Comment by smigielski** [comment]
Thanks for the feedback. I fixed that as you suggest.
